# Generated by Django 5.0.3 on 2024-03-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_age_alter_book_email_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
