# Generated by Django 5.0.3 on 2024-03-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='age',
        ),
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default=10, max_length=100),
        ),
    ]
