# Generated by Django 5.0.3 on 2024-03-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bdate', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='books/images/')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='npages',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author'),
        ),
    ]
